M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu24.04.1} date 2024-07-22T22:19:08+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-22T22:19:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.7394Y-2.1409
X4.9669Y-2.1409
M30
