[target.riscv32imc-esp-espidf]
runner = "espflash flash -M"
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[build]
target = "riscv32imc-esp-espidf"

[env]
MCU="esp32c3"
ESP_IDF_VERSION = "v5.2.2"
SSID = "Chrononauts-Board"
SSID_PASSWORD = "paradoxium2"
CHRONONAUTS_ID = "-1"

[unstable]
build-std = ["std", "panic_abort"]
